version: '3.8'

services:
  simulator:
    image: mars-iot-simulator:multiarch_v1
    ports:
      - "8080:8080"
    networks:
      - mars_net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    environment: # Environment's variable to configuring Apache
      KAFKA_NODE_ID: 1 # Unique ID of the Kafka node in the cluster
      KAFKA_PROCESS_ROLES: broker,controller # controller: manage metadata of the cluster
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 # defines on which port Kafka listen to
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Address communicated to the clients
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # Tells to Kafka which listener use for the controller
    ports:
      - "9092:9092"
    networks:
      - mars_net

networks:
  mars_net:
    driver: bridge
